### ISSUE TITLE
How do I get the textbook topic and chapter in table_of_contents? Do I need prepare it by myself?

### ISSUE THREAD

**Issue by weizier** [SciPhi-AI/synthesizer#104]
I find this project need the table of content but I don't have many of it, does the table_of_content itself be generated by some kind of way also? If so, how do I prepare it?
Thanks!

**Comment by emrgnt-cmplxty** [comment]
there is an example here - https://github.com/SciPhi-AI/sciphi/blob/main/sciphi/data/sample/table_of_contents/Aerodynamics_of_Viscous_Fluids.yaml
